name: context

on: [push]

jobs:
  contextjob:
    runs-on: ubuntu-latest
    env:
      GITHUB_CONTEXT: ${{ toJSON(github) }}
    steps:
      - name: DumpGithub-context
        run: |
          echo "$GITHUB_CONTEXT"
