name: decrypt the file
on: pull_request
jobs:
  decrypt_file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: decrypt-file
        env:
          passpharse: ${{ secrets.PASSPHARSE }}
        run: |
          gpg --quiet --batch --yes --decrypt --passphrase="${passpharse}" --output ${HOME}/gopi.txt gopi_secets.txt.gpg
      - name: print the file
        run: |
          cat ${HOME}/gopi.txt
