name: example-use-action

on: [pull_request]

jobs:
  job-use-action:
    runs-on: ubuntu-latest
    steps:
      - name: try-use-action
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: "hello gopi"

      - name: log-date-output
        run: echo "${{ steps.greet.outputs.time }}"

      - name: list env values
        run: env
